services:
  - type: web
    name: policy-tracker-backend
    env: python
    buildCommand: "cd backend && poetry install --no-dev"
    startCommand: "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      - key: AWS_REGION
        value: "us-east-1"
      - key: ALLOWED_ORIGINS
        value: "https://policy-tracker-platform-frontend.onrender.com,http://localhost:3000"
    
  - type: static
    name: policy-tracker-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://policy-tracker-platform-backend.onrender.com/api

