services:
  - type: web
    name: policy-tracker-backend
    env: python
    rootDir: ./PolicyTracker/backend
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    
  - type: static
    name: policy-tracker-frontend
    buildCommand: "cd PolicyTracker/frontend && npm install && npm run build"
    staticPublishPath: ./PolicyTracker/frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://policy-tracker-backend.onrender.com/api

